import { generateId } from './helpers';

const today = new Date();
const fmt = (d) => d.toISOString().split('T')[0];

function addDays(date, days) {
  const d = new Date(date);
  d.setDate(d.getDate() + days);
  return d;
}

export const mockTemplates = [
  {
    id: generateId(),
    name: 'Promoção Abril - Desconto 20%',
    content: 'Olá {{nome}}! 🎉 Aproveite 20% de desconto em todos os produtos da nossa loja! Use o cupom ABRIL20 até o final do mês. Não perca essa oportunidade!\n\nAcesse: {{link}}\n\nResponda SAIR para não receber mais mensagens.',
    type: 'marketing',
    expiryDate: fmt(addDays(today, 5)),
    updateStartDate: fmt(addDays(today, -2)),
    updateEndDate: fmt(addDays(today, 3)),
    tags: ['promoção', 'desconto', 'abril', 'cupom'],
    notes: 'Mensagem principal do mês. Atualizar cupom e percentual todo mês.',
    manualStatus: null,
    version: 3,
    usageRecommendation: 'WhatsApp Business - Campanhas de vendas mensais',
    category: 'Vendas',
    isFavorite: true,
    history: [
      { date: fmt(addDays(today, -60)), action: 'Criado', user: 'Sistema' },
      { date: fmt(addDays(today, -30)), action: 'Atualizado para Março', user: 'Usuário' },
      { date: fmt(addDays(today, -2)), action: 'Atualizado para Abril', user: 'Usuário' },
    ],
    createdAt: fmt(addDays(today, -60)),
    updatedAt: fmt(addDays(today, -2)),
  },
  {
    id: generateId(),
    name: 'Lembrete de Pagamento',
    content: 'Olá {{nome}}, este é um lembrete amigável sobre sua fatura no valor de R$ {{valor}} com vencimento em {{data_vencimento}}.\n\nPara segunda via, acesse: {{link}}\n\nEm caso de dúvidas, entre em contato conosco.',
    type: 'utility',
    expiryDate: fmt(addDays(today, 30)),
    updateStartDate: fmt(addDays(today, 20)),
    updateEndDate: fmt(addDays(today, 28)),
    tags: ['pagamento', 'fatura', 'lembrete', 'cobrança'],
    notes: 'Mensagem de cobrança recorrente. Verificar link da segunda via mensalmente.',
    manualStatus: null,
    version: 5,
    usageRecommendation: 'WhatsApp Business - Cobranças e lembretes',
    category: 'Financeiro',
    isFavorite: true,
    history: [
      { date: fmt(addDays(today, -150)), action: 'Criado', user: 'Sistema' },
      { date: fmt(addDays(today, -10)), action: 'Revisado', user: 'Usuário' },
    ],
    createdAt: fmt(addDays(today, -150)),
    updatedAt: fmt(addDays(today, -10)),
  },
  {
    id: generateId(),
    name: 'Boas-vindas Novo Cliente',
    content: 'Seja bem-vindo(a), {{nome}}! 😊\n\nEstamos muito felizes em ter você conosco. Aqui está tudo o que você precisa saber para começar:\n\n📋 Seu código de cliente: {{codigo}}\n📞 Suporte: {{telefone}}\n🌐 Portal: {{link}}\n\nQualquer dúvida, estamos à disposição!',
    type: 'utility',
    expiryDate: fmt(addDays(today, 90)),
    updateStartDate: fmt(addDays(today, 80)),
    updateEndDate: fmt(addDays(today, 88)),
    tags: ['boas-vindas', 'onboarding', 'novo cliente', 'cadastro'],
    notes: 'Template de onboarding. Raramente precisa de atualização.',
    manualStatus: null,
    version: 2,
    usageRecommendation: 'WhatsApp Business - Fluxo de cadastro',
    category: 'Atendimento',
    isFavorite: false,
    history: [
      { date: fmt(addDays(today, -120)), action: 'Criado', user: 'Sistema' },
      { date: fmt(addDays(today, -45)), action: 'Atualizado telefone', user: 'Usuário' },
    ],
    createdAt: fmt(addDays(today, -120)),
    updatedAt: fmt(addDays(today, -45)),
  },
  {
    id: generateId(),
    name: 'Promoção Março - Frete Grátis',
    content: 'Olá {{nome}}! 🚚 Frete GRÁTIS em todas as compras acima de R$99! Promoção válida até 31/03.\n\nCompre agora: {{link}}\n\nResponda SAIR para não receber mais mensagens.',
    type: 'marketing',
    expiryDate: fmt(addDays(today, -8)),
    updateStartDate: fmt(addDays(today, -15)),
    updateEndDate: fmt(addDays(today, -5)),
    tags: ['promoção', 'frete grátis', 'março'],
    notes: 'Campanha de março encerrada. Duplicar para abril se necessário.',
    manualStatus: null,
    version: 1,
    usageRecommendation: 'WhatsApp Business - Campanhas sazonais',
    category: 'Vendas',
    isFavorite: false,
    history: [
      { date: fmt(addDays(today, -40)), action: 'Criado', user: 'Sistema' },
    ],
    createdAt: fmt(addDays(today, -40)),
    updatedAt: fmt(addDays(today, -40)),
  },
  {
    id: generateId(),
    name: 'Confirmação de Agendamento',
    content: 'Olá {{nome}}! ✅ Seu agendamento foi confirmado.\n\n📅 Data: {{data}}\n🕐 Horário: {{horario}}\n📍 Local: {{endereco}}\n\nPara cancelar ou reagendar, responda esta mensagem ou ligue para {{telefone}}.',
    type: 'utility',
    expiryDate: fmt(addDays(today, 3)),
    updateStartDate: fmt(addDays(today, -5)),
    updateEndDate: fmt(addDays(today, 1)),
    tags: ['agendamento', 'confirmação', 'consulta'],
    notes: 'Atualizar endereço quando houver mudança de sede.',
    manualStatus: 'updating',
    version: 4,
    usageRecommendation: 'WhatsApp Business - Confirmações automáticas',
    category: 'Atendimento',
    isFavorite: true,
    history: [
      { date: fmt(addDays(today, -200)), action: 'Criado', user: 'Sistema' },
      { date: fmt(addDays(today, -1)), action: 'Em atualização', user: 'Usuário' },
    ],
    createdAt: fmt(addDays(today, -200)),
    updatedAt: fmt(addDays(today, -1)),
  },
  {
    id: generateId(),
    name: 'Pesquisa de Satisfação',
    content: 'Olá {{nome}}! Gostaríamos de saber como foi sua experiência conosco.\n\nAvalie nosso atendimento de 1 a 5:\n⭐ 1 - Péssimo\n⭐⭐ 2 - Ruim\n⭐⭐⭐ 3 - Regular\n⭐⭐⭐⭐ 4 - Bom\n⭐⭐⭐⭐⭐ 5 - Excelente\n\nSua opinião é muito importante para nós!',
    type: 'utility',
    expiryDate: fmt(addDays(today, 60)),
    updateStartDate: fmt(addDays(today, 50)),
    updateEndDate: fmt(addDays(today, 58)),
    tags: ['pesquisa', 'satisfação', 'NPS', 'feedback'],
    notes: 'Enviada automaticamente após atendimento. Revisar escala periodicamente.',
    manualStatus: null,
    version: 2,
    usageRecommendation: 'WhatsApp Business - Pós-atendimento',
    category: 'Qualidade',
    isFavorite: false,
    history: [
      { date: fmt(addDays(today, -90)), action: 'Criado', user: 'Sistema' },
      { date: fmt(addDays(today, -20)), action: 'Revisado', user: 'Usuário' },
    ],
    createdAt: fmt(addDays(today, -90)),
    updatedAt: fmt(addDays(today, -20)),
  },
];
